name: remote ssh command for deploy
on:
  push:
    branches:
      - develop
      - main
      - test/github_actions
    paths-ignore:
      - 'README.md'

jobs:
  build-dev:
    name: deploy-dev
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/develop' }}
    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: localhost
          #host: ${{ secrets.HOST }} NOTE: 현재 EC2 서버에서 main/develop 두개 구동되고 있으므로 SSL은 EC2 서버에서 적용
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            ./build-dev.sh

  build:
    name: deploy
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: localhost
          #host: ${{ secrets.HOST }} NOTE: 현재 EC2 서버에서 main/develop 두개 구동되고 있으므로 SSL은 EC2 서버에서 적용
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            ./build.sh
